use std::path::Path;

use lofty::prelude::*;
use lofty::probe::Probe;
use lofty::tag::ItemKey;
use serde_json::json;
use tempfile::tempdir;

use crate::models::{Show, Track};
use crate::tagger::tag_track;

/// Silence FLAC fixture (generated by ffmpeg: anullsrc mono 44.1kHz, 0.01s).
const SILENCE_FLAC: &[u8] = include_bytes!("../../tests/fixtures/silence.flac");

/// Create a test FLAC file by copying the fixture.
fn create_test_flac(path: &Path) {
    std::fs::write(path, SILENCE_FLAC).unwrap();
}

fn sample_show() -> Show {
    Show::from_json(&json!({
        "containerID": 99999,
        "artistName": "Phish",
        "artistID": 196,
        "containerInfo": "2024-08-31 Dick's Sporting Goods Park",
        "venueName": "Dick's Sporting Goods Park",
        "venueCity": "Commerce City",
        "venueState": "CO",
        "performanceDate": "2024-08-31",
        "performanceDateFormatted": "08/31/2024",
        "performanceDateYear": "2024",
        "tracks": [
            {"trackID": 1, "songTitle": "Tweezer", "trackNum": 1, "setNum": 1},
            {"trackID": 2, "songTitle": "Sand", "trackNum": 2, "setNum": 1}
        ]
    }))
}

fn sample_track() -> Track {
    serde_json::from_value(json!({
        "trackID": 12345,
        "songID": 678,
        "songTitle": "Tweezer",
        "trackNum": 1,
        "discNum": 1,
        "setNum": 1
    }))
    .unwrap()
}

#[test]
fn test_tag_flac_standard_fields() {
    let dir = tempdir().unwrap();
    let path = dir.path().join("test.flac");
    create_test_flac(&path);

    let show = sample_show();
    let track = sample_track();

    tag_track(&path, &show, &track).unwrap();

    // Read back tags
    let tagged = Probe::open(&path).unwrap().read().unwrap();
    let tag = tagged.primary_tag().unwrap();

    assert_eq!(tag.title().as_deref(), Some("Tweezer"));
    assert_eq!(tag.artist().as_deref(), Some("Phish"));
    assert_eq!(
        tag.album().as_deref(),
        Some("2024-08-31 Dick's Sporting Goods Park")
    );
}

#[test]
fn test_tag_flac_track_number() {
    let dir = tempdir().unwrap();
    let path = dir.path().join("test.flac");
    create_test_flac(&path);

    let show = sample_show();
    let track = sample_track();

    tag_track(&path, &show, &track).unwrap();

    let tagged = Probe::open(&path).unwrap().read().unwrap();
    let tag = tagged.primary_tag().unwrap();

    assert_eq!(tag.get_string(&ItemKey::TrackNumber), Some("1"));
    assert_eq!(tag.get_string(&ItemKey::TrackTotal), Some("2")); // 2 tracks in show
}

#[test]
fn test_tag_flac_disc_number() {
    let dir = tempdir().unwrap();
    let path = dir.path().join("test.flac");
    create_test_flac(&path);

    let show = sample_show();
    let track = sample_track();

    tag_track(&path, &show, &track).unwrap();

    let tagged = Probe::open(&path).unwrap().read().unwrap();
    let tag = tagged.primary_tag().unwrap();

    assert_eq!(tag.get_string(&ItemKey::DiscNumber), Some("1"));
    assert_eq!(tag.get_string(&ItemKey::DiscTotal), Some("1"));
}

#[test]
fn test_tag_flac_date() {
    let dir = tempdir().unwrap();
    let path = dir.path().join("test.flac");
    create_test_flac(&path);

    let show = sample_show();
    let track = sample_track();

    tag_track(&path, &show, &track).unwrap();

    let tagged = Probe::open(&path).unwrap().read().unwrap();
    let tag = tagged.primary_tag().unwrap();

    assert_eq!(tag.get_string(&ItemKey::RecordingDate), Some("2024-08-31"));
}

#[test]
fn test_tag_nonexistent_file_returns_error() {
    let dir = tempdir().unwrap();
    let path = dir.path().join("nonexistent.flac");

    let show = sample_show();
    let track = sample_track();

    let result = tag_track(&path, &show, &track);
    assert!(result.is_err());
}

#[test]
fn test_tag_invalid_file_returns_error() {
    let dir = tempdir().unwrap();
    let path = dir.path().join("garbage.flac");
    std::fs::write(&path, b"not a real flac file").unwrap();

    let show = sample_show();
    let track = sample_track();

    let result = tag_track(&path, &show, &track);
    assert!(result.is_err());
}
